spring.application.name=ImplantaHub
spring.datasource.url=jdbc:postgresql://localhost:5432/implantahub
spring.datasource.username=implantahub
spring.datasource.password=implantahub

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false